### ISSUE TITLE
请教如果content里面写了控制器，如何动态绑定，目前没效果

### ISSUE THREAD

**Issue by wandergis** [think2011/ng-layer#1]
如果content里面的字符串是如下的内容，
![image](https://cloud.githubusercontent.com/assets/5799374/12260474/def9fdfa-b956-11e5-9f73-e9994c473783.png)
如何使得angular能正确解析这块啊？

**Comment by think2011** [comment]
不支持这种方式，封装的核心就是通过传入的$scope渲染里面的内容。

如果需要传入controller的方式的话，可以看看 ng-model 这个插件，它是传入controller的方式的。

**Comment by think2011** [comment]
写错啦，是这个 https://github.com/btford/angular-modal

**Comment by wandergis** [comment]
@think2011 太感谢了，我试试

**Comment by wandergis** [comment]
参照另外一个库稍微修改了下你的代码，目前已经支持我上面那种形式了，需要我发pull requests么

**Comment by think2011** [comment]
写这个的最初的想法是在controller里面调用的，所以传入$scope来渲染content。

方便的话，PR上来吧，看看你的想法 😄
